### ISSUE TITLE
Missing assets folder.

### ISSUE THREAD

**Issue by VitoKingg** [nicopap/cuicui_layout#37]
When I run `cargo run --bin ui_debug`, it encountered an error of `reading an asset: path not found: ../../assets/***.png`.

It seems that you add `/assets` in the .gitingore file.

And I think you should add `/target` in your .gitignore file.

**Comment by nicopap** [comment]
Ooops my bad, I'll fix this quick

**Comment by nicopap** [comment]
Fixed by efb03d7
